### ISSUE TITLE
添加官方市场的图源

### ISSUE THREAD

**Issue by nosnakeob** [TminiK/Picbox#1]
能不能把h-viewer的官方市场搬到这里，毕竟有些规则能用但是这里没有

**Comment by TminiK** [comment]
可以自己添加hv的图源市场：https://raw.githubusercontent.com/H-Viewer-Sites/Index/master/source.json

**Comment by TminiK** [comment]
> 能不能把h-viewer的官方市场搬到这里，毕竟有些规则能用但是这里没有

可以在图源市场自己添加hv的图源市场地址：https://raw.githubusercontent.com/H-Viewer-Sites/Index/master/source.json
